[settings]
experimental = true

[env]

[env._]
source = [
  ".envrc.local-default",
  ".envrc",
]

[hooks]
enter = [
  "echo '[.envrc.local-default, .envrc] 파일에 정의된 환경 변수가 순차적으로 적용 되었어요.'",
  "echo 'mise set 명령어를 통해 확인할 수 있어요.'",
]

leave = [
  "echo '셋팅 되었던 환경 변수를 해제했어요.'",
]

