replicaCount: 1
image:
  repository: "seaproject/my-app"
  tag: "latest"
host: "test.intellisia.site"
port: 80 # 또는 seaproject/my-app의 실제 포트
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"