replicaCount: 1
image:
  repository: "seaproject/my-app"
  tag: "latest"
  pullPolicy: IfNotPresent
host: "testproject2.intellisia.site"
port: 3000
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
