apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment 
spec:
  replicas: {{ required "replicaCount 까묵지 말라고 했지!" .Values.replicaCount }}
  selector:
    matchLabels:
      app: cicd-practice 
  template:
    metadata:
      labels:
        app: cicd-practice
    spec:
      containers:
      - name: my-container
        image: {{ required "image 까묵지 말라고 했지!" .Values.image }}
        ports:
        - containerPort: {{ .Values.port }}
        resources: {{ toYaml .Values.resources | nindent 10 }}